### ISSUE TITLE
论文问题请教

### ISSUE THREAD

**Issue by czhxiaohuihui** [HabbakukWang1103/SAN#1]
您好，

您的这篇论文中，在进行图像和文本特征学习时有一对一的学习过程，就是拿图像的特征v去guide文本特征的学习，这样的话，训练时，比如 batch_size=128,  考虑图像和文本一对一的关系，每幅图像和128个文本进行特征学习，时间复杂度会很高。

 在测试时，比如MS COCO 5K，图像和文本进行一对一学习，这样时间复杂度也会很高。。

不知道你在实验时是怎么处理这个问题的。

非常感谢

**Comment by HabbakukWang1103** [comment]
我在训练的时候的fix visual CNN的参数，根据我的观察，两个attention模块并没有增加很多的时间开销。而且我的模型10个epoch内就能收敛，比起VSE++的baseline并不需要更多的训练时间。test时的时间应该会比baseline多一点，我当时没具体统计，几分钟内可以测完。

**Comment by czhxiaohuihui** [comment]
训练时，因为你论文中学习特征的方式是Pairwise的，图像特征和文本特征一对一进行学习，一个batch的128个(Image, Text)对，每个Image和128个Text进行特征学习，然后又有128个Image，特征学习的过程就是128*128对图像和文本的特征的学习，我指的是这个时间开销。

而VSE++，图像和文本的特征学习是单独的，没有这种Pairwise的过程，每batch的128个(Image, Text)对，Image和Text分别输入到CNN和LSTM就可以得到对应的特征，这里的时间开销就只有O(batch_size)，在你的论文中应该是O(batch_size^2)

**Comment by HabbakukWang1103** [comment]
你分析的没错。我在训练中实际时间开销并没有因此增大很多，没太关注这方面，因为现在基于multi-modal或者cross-modal attention的方法很多都会有类似的情况出现。
